# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Disable dnf module postgresql
  command: dnf module disable postgresql -y
  args:
    warn: no
  when:
    - ansible_distribution_major_version | int > 7 and ansible_distribution != 'Ubuntu'
  register: dnf_result
  changed_when: '"Disabling modules" in dnf_result.stdout'
  notify: yum makecache

- import_tasks: public_repo.yml

- name: Install PostgreSQL packages
  yum:
    name: "{{ postgresql_default_packages['common'] + postgresql_default_packages[packages_version] }}"
    state: present
  vars:
    packages_version: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('legacy','modern') }}"
  when: ansible_distribution != 'Ubuntu'


- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    id: "ACCC4CF8"
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: "Add  apt repository"
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: "pgdg"
  when: ansible_distribution == "Ubuntu"
  
- name: "Generated by Ansible"
  lineinfile:
    dest: /etc/apt/sources.list.d/pgdg.list
    insertbefore: BOF
    line: '###Managed By Ansible###'
  when: ansible_distribution == "Ubuntu"
  ignore_errors: yes

#- debug: var={{ pkg_config.source_lists[0].repo_url }}

- name: Install common packages {{ ansible_distribution }}
  apt:
    name:
      - "postgresql-11"
      - "python-pexpect"
    state: present
  when: ansible_distribution == 'Ubuntu'